import type { Metadata } from "next";
import { lusitana } from "@/src/app/ui/fonts";
import { Year, cn } from "@/src/app/lib/utils";
import "./globals.css";
import { Figtree } from "next/font/google";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", figtree.variable)}>
      <body className={`${lusitana.className} antialiased`}>
        {children}
      </body>
      
    </html>
  );
}
